/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const VisitorCommentLazyImport = createFileRoute('/visitorComment')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const VisitorCommentLazyRoute = VisitorCommentLazyImport.update({
  id: '/visitorComment',
  path: '/visitorComment',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/visitorComment.lazy').then((d) => d.Route),
)

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/visitorComment': {
      id: '/visitorComment'
      path: '/visitorComment'
      fullPath: '/visitorComment'
      preLoaderRoute: typeof VisitorCommentLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/visitorComment': typeof VisitorCommentLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/visitorComment': typeof VisitorCommentLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/visitorComment': typeof VisitorCommentLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/visitorComment'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/visitorComment'
  id: '__root__' | '/' | '/visitorComment'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  VisitorCommentLazyRoute: typeof VisitorCommentLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  VisitorCommentLazyRoute: VisitorCommentLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/visitorComment"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/visitorComment": {
      "filePath": "visitorComment.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
